### ISSUE TITLE
Add elixir support

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/syntect_server#27]
Elixir is pretty popular and close to erlang. Looks like we don't support it currently:

https://sourcegraph.com/github.com/phoenixframework/phoenix/-/blob/lib/mix/phoenix.ex

**Comment by mmmries** [comment]
I just started looking into using this project to syntax highlight my personal blog where I use a decent amount of Elixir. Is there a good place for me to start looking to see if I can get this added?

**Comment by camdencheek** [comment]
This was fixed in 331beda2
