### ISSUE TITLE
Terraform (HCL) support

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/syntect_server#40]
We've had a request to highlight Terraform's `.tf` files, which uses the HCL config language. A grammar can be found [here](https://github.com/alexlouden/Terraform.tmLanguage).

**Comment by rvantonder** [comment]
I'm finding we do highlight `.tf`, is there an example that doesn't work? [example](https://sourcegraph.com/github.com/Kong/kong/-/blob/spec/fixtures/perf/terraform/equinix-metal/ssh.tf?subtree=true)

**Comment by rvantonder** [comment]
Think this is done recently in https://github.com/sourcegraph/sourcegraph/pull/22040. Closing this unless we find an example that doesn't work.
